import type { Metadata } from 'next';
import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import { SwapTokenContextProvider } from '@/context/swap-context';
import { Navbar } from '@/components';
import { cn } from '@/utils';
import { Inter, EB_Garamond } from 'next/font/google';
import { Providers } from '@/context/providers';


const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const eb_garamond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-heading',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(inter.variable, eb_garamond.variable)}>
    <body className="min-h-[calc(100vh-1px)] flex flex-col font-sans bg-brand-50 text-brand-950 antialiased">
    <Providers>
      <SwapTokenContextProvider>
        <main className="relative flex-1 flex flex-col">
          <Navbar></Navbar>
          {children}
        </main>
      </SwapTokenContextProvider>
    </Providers>
    </body>
    </html>

  );
}
